#!/bin/bash

a2ensite miolo

echo -e "\n#Miolo configuration\n127.0.0.1    miolo.localhost" >> /etc/hosts

# change the log directory owner
chown -R www-data /var/www/miolo/var/log/

/etc/init.d/apache2 reload
