{
    PRINT_FILE: "Aguarde a geração do relatório.\nO resultado será exibido em uma nova janela.",
    PRINT_PDF: "Aguarde a geração do arquivo PDF.\nO resultado será exibido em uma nova janela.",
    ITEM_EXISTS_ON_LIST: "Item já está na lista!",
    ERROR_DETECTED: "O seguinte erro foi detectado",
    ERRORS_DETECTED: "Os seguintes erros foram detectados",
    FIELD_IS_REQUIRED: "O campo \"${field}\" deve ser informado",
    VALIDATE_MIN: "O campo \"${field}\" deve conter no mínimo ${min} caracteres",
    VALIDATE_MAX: "O campo \"${field}\" deve conter no máximo ${max} caracteres",
    INVALID_CHAR: "O caractere \"${character}\" é inválido para o campo \"${field}\"",
    VALIDATE_LENGTH: "O campo \"${field}\" deve conter ${length} caracteres",
    VALIDATE_NUM_POSITION: "O campo \"${field}\" deve conter um dígito numérico na posição ${index}",
    VALIDATE_CHAR_POSITION: "O campo \"${field}\" deve conter o caractere ${character} na posição ${index}",
    INVALID_FIELD_CONTENT: "O conteúdo do campo \"${field}\" é inválido!",
    DATE_FORMAT: "O formato da data deve ser: ${format}",
    INVALID_DAY: "O dia informado é inválido.",
    INVALID_MONTH: "O mês informado é inválido.",
    INVALID_YEAR: "O ano deve conter 4 dígitos e estar entre ${min} e ${max}",
    INFORM_A_VALID_DATE: "Informe uma data válida."
}