DROP TYPE IF EXISTS DisciplinasSemestre CASCADE;
CREATE TYPE DisciplinasSemestre AS (
    curriculumId INT,
    semester INT,
    curricularComponentId VARCHAR,
    curricularComponentVersion INT,
    curricularComponentName TEXT,
    turnId INT,
    turnDescription VARCHAR,
    unitId INT,
    unitDescription VARCHAR,
    groupId INT,
    classId VARCHAR,
    periodId VARCHAR,
    learningPeriodId INT,
    totalEnrolled INT,
    vacant INT,
    regimenId INT,
    regimenDescription TEXT,
    startDate TEXT,
    endDate TEXT,
    className TEXT,
    enrollId INT,
    enrollStatusId INT,
    enrollStatusDescription TEXT,
    academiCredits DOUBLE PRECISION,
    lessonNumberHours DOUBLE PRECISION,
    curricularComponentTypeId INT,
    academicNumberHours DOUBLE PRECISION,
    possuiVinculo BOOLEAN,
    curriculumTypeId INT,
    curriculumTypeDescription TEXT,
    curricularComponentTypeDescription TEXT,
    courseId VARCHAR,
    courseVersion VARCHAR,
    courseName VARCHAR,
    estaPendente BOOLEAN
);