DROP TYPE IF EXISTS ClassificacaoMatricula CASCADE;
CREATE TYPE ClassificacaoMatricula AS (
    posicao TEXT,
    codigo_aluno BIGINT,
    nome_aluno VARCHAR,
    codigo_curso_disciplina_oferecida VARCHAR,
    versao_curso_disciplina_oferecida INT,
    codigo_turno_disciplina_oferecida INT,
    turno_disciplina_oferecida VARCHAR,
    codigo_unidade_disciplina_oferecida INT,
    unidade_disciplina_oferecida VARCHAR,
    status_atual_na_disciplina_oferecida TEXT,
    e_disciplina_do_curso BOOLEAN,
    coeficiente_de_classificacao NUMERIC,
    data_da_matricula_na_disciplina_oferecida DATE,
    horario_da_matricula_na_disciplina_oferecida TIME WITHOUT TIME ZONE,
    status_previsto TEXT,
    codigo_contrato INT,
    classificado_na_disciplina_oferecida BOOLEAN,
    vagas_disciplina_oferecida INT,
    codigo_curso_contrato VARCHAR,
    curso_contrato VARCHAR,
    versao_curso_contrato INT,
    codigo_turno_contrato INT,
    turno_contrato VARCHAR,
    codigo_unidade_contrato INT,
    unidade_contrato VARCHAR,
    codigo_disciplina_oferecida INT,
    codigo_disciplina VARCHAR,
    versao_disciplina INT,
    disciplina TEXT
);
