create or replace view view_pedagogico_oficio_anac as
Select distinct
acpinscricao.username as acpinscricao_username,
acpinscricao.datetime as acpinscricao_datetime,
acpinscricao.ipaddress as acpinscricao_ipaddress,
acpinscricao.inscricaoid as acpinscricao_inscricaoid,
acpinscricaoturmagrupo.ofertaturmaid as acpinscricao_ofertaturmaid,
acpinscricao.personid as acpinscricao_personid,
acpinscricao.situacao as acpinscricao_situacao,
acpinscricao.datasituacao as acpinscricao_datasituacao,
acpinscricao.origem as acpinscricao_origem,
--acpinscricao.precocursoid as acpinscricao_precocursoid,
acpinscricao.diadevencimentoid as acpinscricao_diadevencimentoid,
acpinscricaoturmagrupo.precocondicaomatriculaid as acpinscricao_precocondicaomatriculaid,
--acpinscricao.precocondicaoinscricaoid as acpinscricao_precocondicaoinscricaoid,
acpinscricao.unitid as acpinscricao_unitid,
basphysicalpersonstudent.username as basphysicalpersonstudent_username,
basphysicalpersonstudent.datetime as basphysicalpersonstudent_datetime,
basphysicalpersonstudent.ipaddress as basphysicalpersonstudent_ipaddress,
basphysicalpersonstudent.personid as basphysicalpersonstudent_personid,
basphysicalpersonstudent.persondv as basphysicalpersonstudent_persondv,
basphysicalpersonstudent.personmask as basphysicalpersonstudent_personmask,
basphysicalpersonstudent.name as basphysicalpersonstudent_name,
basphysicalpersonstudent.shortname as basphysicalpersonstudent_shortname,
basphysicalpersonstudent.cityid as basphysicalpersonstudent_cityid,
basphysicalpersonstudent.zipcode as basphysicalpersonstudent_zipcode,
basphysicalpersonstudent.location as basphysicalpersonstudent_location,
basphysicalpersonstudent.number as basphysicalpersonstudent_number,
basphysicalpersonstudent.complement as basphysicalpersonstudent_complement,
basphysicalpersonstudent.neighborhood as basphysicalpersonstudent_neighborhood,
basphysicalpersonstudent.email as basphysicalpersonstudent_email,
basphysicalpersonstudent.emailalternative as basphysicalpersonstudent_emailalternative,
basphysicalpersonstudent.url as basphysicalpersonstudent_url,
basphysicalpersonstudent.datein as basphysicalpersonstudent_datein,
basphysicalpersonstudent.password as basphysicalpersonstudent_password,
basphysicalpersonstudent.isallowpersonaldata as basphysicalpersonstudent_isallowpersonaldata,
basphysicalpersonstudent.miolousername as basphysicalpersonstudent_miolousername,
basphysicalpersonstudent.locationtypeid as basphysicalpersonstudent_locationtypeid,
basphysicalpersonstudent.sentemail as basphysicalpersonstudent_sentemail,
basphysicalpersonstudent.photoid as basphysicalpersonstudent_photoid,
basphysicalpersonstudent.login as basphysicalpersonstudent_login,
basphysicalpersonstudent.obs as basphysicalpersonstudent_obs,
basphysicalpersonstudent.sex as basphysicalpersonstudent_sex,
basphysicalpersonstudent.maritalstatusid as basphysicalpersonstudent_maritalstatusid,
basphysicalpersonstudent.residentialphone as basphysicalpersonstudent_residentialphone,
basphysicalpersonstudent.workphone as basphysicalpersonstudent_workphone,
basphysicalpersonstudent.cellphone as basphysicalpersonstudent_cellphone,
basphysicalpersonstudent.messagephone as basphysicalpersonstudent_messagephone,
basphysicalpersonstudent.messagecontact as basphysicalpersonstudent_messagecontact,
basphysicalpersonstudent.datebirth as basphysicalpersonstudent_datebirth,
basphysicalpersonstudent.cityidbirth as basphysicalpersonstudent_cityidbirth,
basphysicalpersonstudent.countryidbirth as basphysicalpersonstudent_countryidbirth,
basphysicalpersonstudent.responsablelegalid as basphysicalpersonstudent_responsablelegalid,
basphysicalpersonstudent.carplate as basphysicalpersonstudent_carplate,
basphysicalpersonstudent.specialnecessityid as basphysicalpersonstudent_specialnecessityid,
basphysicalpersonstudent.specialnecessitydescription as basphysicalpersonstudent_specialnecessitydescription,
basphysicalpersonstudent.cityidwork as basphysicalpersonstudent_cityidwork,
basphysicalpersonstudent.zipcodework as basphysicalpersonstudent_zipcodework,
basphysicalpersonstudent.locationwork as basphysicalpersonstudent_locationwork,
basphysicalpersonstudent.complementwork as basphysicalpersonstudent_complementwork,
basphysicalpersonstudent.neighborhoodwork as basphysicalpersonstudent_neighborhoodwork,
basphysicalpersonstudent.ethnicoriginid as basphysicalpersonstudent_ethnicoriginid,
basphysicalpersonstudent.datedeath as basphysicalpersonstudent_datedeath,
basphysicalpersonstudent.persontitleid as basphysicalpersonstudent_persontitleid,
basphysicalpersonstudent.locationtypeidwork as basphysicalpersonstudent_locationtypeidwork,
basphysicalpersonstudent.mothername as basphysicalpersonstudent_mothername,
basphysicalpersonstudent.fathername as basphysicalpersonstudent_fathername,
basphysicalpersonstudent.workemployername as basphysicalpersonstudent_workemployername,
basphysicalpersonstudent.workfunction as basphysicalpersonstudent_workfunction,
basphysicalpersonstudent.workstartdate as basphysicalpersonstudent_workstartdate,
basphysicalpersonstudent.workenddate as basphysicalpersonstudent_workenddate,
basphysicalpersonstudent.workathome as basphysicalpersonstudent_workathome,
basphysicalpersonstudent.ethnicorigin as basphysicalpersonstudent_ethnicorigin,
basphysicalpersonstudent.identifier as basphysicalpersonstudent_identifier,
basphysicalpersonstudent.namesearch as basphysicalpersonstudent_namesearch,
basphysicalpersonstudent.externalcourseidhs as basphysicalpersonstudent_externalcourseidhs,
basphysicalpersonstudent.institutionidhs as basphysicalpersonstudent_institutionidhs,
basphysicalpersonstudent.cityidhs as basphysicalpersonstudent_cityidhs,
basphysicalpersonstudent.yearhs as basphysicalpersonstudent_yearhs,
basphysicalpersonstudent.isinsured as basphysicalpersonstudent_isinsured,
basphysicalpersonstudent.passive as basphysicalpersonstudent_passive,
basperson.username as basperson_username,
basperson.datetime as basperson_datetime,
basperson.ipaddress as basperson_ipaddress,
basperson.personid as basperson_personid,
basperson.persondv as basperson_persondv,
basperson.personmask as basperson_personmask,
basperson.name as basperson_name,
basperson.shortname as basperson_shortname,
basperson.cityid as basperson_cityid,
basperson.zipcode as basperson_zipcode,
basperson.location as basperson_location,
basperson.number as basperson_number,
basperson.complement as basperson_complement,
basperson.neighborhood as basperson_neighborhood,
basperson.email as basperson_email,
basperson.emailalternative as basperson_emailalternative,
basperson.url as basperson_url,
basperson.datein as basperson_datein,
basperson.password as basperson_password,
basperson.isallowpersonaldata as basperson_isallowpersonaldata,
basperson.miolousername as basperson_miolousername,
basperson.locationtypeid as basperson_locationtypeid,
basperson.sentemail as basperson_sentemail,
basperson.photoid as basperson_photoid,
basperson.login as basperson_login,
--basperson.obs as basperson_obs,
basdocument.username as basdocument_username,
basdocument.datetime as basdocument_datetime,
basdocument.ipaddress as basdocument_ipaddress,
basdocument.personid as basdocument_personid,
basdocument.documenttypeid as basdocument_documenttypeid,
basdocument.content as basdocument_content,
basdocument.isdelivered as basdocument_isdelivered,
basdocument.cityid as basdocument_cityid,
basdocument.organ as basdocument_organ,
basdocument.dateexpedition as basdocument_dateexpedition,
basdocument.obs as basdocument_obs,
basdocument.isexcused as basdocument_isexcused,
basdocumenttype.username as basdocumenttype_username,
basdocumenttype.datetime as basdocumenttype_datetime,
basdocumenttype.ipaddress as basdocumenttype_ipaddress,
basdocumenttype.documenttypeid as basdocumenttype_documenttypeid,
basdocumenttype.name as basdocumenttype_name,
basdocumenttype.mask as basdocumenttype_mask,
basdocumenttype.sex as basdocumenttype_sex,
basdocumenttype.persontype as basdocumenttype_persontype,
basdocumenttype.minage as basdocumenttype_minage,
basdocumenttype.maxage as basdocumenttype_maxage,
basdocumenttype.needdeliver as basdocumenttype_needdeliver,
basdocumenttype.isblockenroll as basdocumenttype_isblockenroll,
basdocumenttype.fillhint as basdocumenttype_fillhint,
basdocumenttype.exigepreenchimento as basdocumenttype_exigepreenchimento,
acpofertaturma.username as acpofertaturma_username,
acpofertaturma.datetime as acpofertaturma_datetime,
acpofertaturma.ipaddress as acpofertaturma_ipaddress,
acpofertaturma.situacao as acpofertaturma_situacao,
acpofertaturma.codigo as acpofertaturma_codigo,
acpofertaturma.ofertaturmaid as acpofertaturma_ofertaturmaid,
acpofertaturma.ofertaturmaanteriorid as acpofertaturma_ofertaturmaanteriorid,
acpofertaturma.ofertacursoid as acpofertaturma_ofertacursoid,
acpofertaturma.descricao as acpofertaturma_descricao,
acpofertaturma.minimoalunos as acpofertaturma_minimoalunos,
acpofertaturma.maximoalunos as acpofertaturma_maximoalunos,
acpofertaturma.unitid as acpofertaturma_unitid,
acpofertaturma.datainicialoferta as acpofertaturma_datainicialoferta,
acpofertaturma.datafinaloferta as acpofertaturma_datafinaloferta,
acpofertaturma.dataencerramento as acpofertaturma_dataencerramento,
acpofertaturma.datainicialaulas as acpofertaturma_datainicialaulas,
acpofertaturma.datafinalaulas as acpofertaturma_datafinalaulas,
acpofertaturma.datainicialinscricao as acpofertaturma_datainicialinscricao,
acpofertaturma.datafinalinscricao as acpofertaturma_datafinalinscricao,
acpofertaturma.datainicialmatricula as acpofertaturma_datainicialmatricula,
acpofertaturma.datafinalmatricula as acpofertaturma_datafinalmatricula,
acpofertaturma.gradehorarioid as acpofertaturma_gradehorarioid,
acpofertacomponentecurricular.username as acpofertacomponentecurricular_username,
acpofertacomponentecurricular.datetime as acpofertacomponentecurricular_datetime,
acpofertacomponentecurricular.ipaddress as acpofertacomponentecurricular_ipaddress,
acpofertacomponentecurricular.ofertacomponentecurricularid as acpofertacomponentecurricular_ofertacomponentecurricularid,
acpofertacomponentecurricular.ofertaturmaid as acpofertacomponentecurricular_ofertaturmaid,
acpofertacomponentecurricular.datainicio as acpofertacomponentecurricular_datainicio,
acpofertacomponentecurricular.datafechamento as acpofertacomponentecurricular_datafechamento,
acpofertacomponentecurricular.unitid as acpofertacomponentecurricular_unitid,
acpofertacomponentecurricular.componentecurricularmatrizid as acpofertacomponentecurricular_componentecurricularmatrizid,
acpofertacurso.username as acpofertacurso_username,
acpofertacurso.datetime as acpofertacurso_datetime,
acpofertacurso.ipaddress as acpofertacurso_ipaddress,
acpofertacurso.ofertacursoid as acpofertacurso_ofertacursoid,
acpofertacurso.ocorrenciacursoid as acpofertacurso_ocorrenciacursoid,
acpofertacurso.descricao as acpofertacurso_descricao,
acpofertacurso.dataencerramento as acpofertacurso_dataencerramento,
acpofertacurso.situacao as acpofertacurso_situacao,
acpofertacurso.taxainscricao as acpofertacurso_taxainscricao,
acpofertacurso.unitid as acpofertacurso_unitid,
acpocorrenciacurso.username as acpocorrenciacurso_username,
acpocorrenciacurso.datetime as acpocorrenciacurso_datetime,
acpocorrenciacurso.ipaddress as acpocorrenciacurso_ipaddress,
acpocorrenciacurso.ocorrenciacursoid as acpocorrenciacurso_ocorrenciacursoid,
acpocorrenciacurso.unitid as acpocorrenciacurso_unitid,
acpocorrenciacurso.situacao as acpocorrenciacurso_situacao,
--acpocorrenciacurso.dataextincao as acpocorrenciacurso_dataextincao,
--acpocorrenciacurso.datainativo as acpocorrenciacurso_datainativo,
acpocorrenciacurso.cursoid as acpocorrenciacurso_cursoid,
acpocorrenciacurso.turnid as acpocorrenciacurso_turnid,
acpcurso.username as acpcurso_username,
acpcurso.datetime as acpcurso_datetime,
acpcurso.ipaddress as acpcurso_ipaddress,
acpcurso.cursoid as acpcurso_cursoid,
acpcurso.cursorepresentanteid as acpcurso_cursorepresentanteid,
acpcurso.grauacademicoid as acpcurso_grauacademicoid,
acpcurso.perfilcursoid as acpcurso_perfilcursoid,
acpcurso.codigo as acpcurso_codigo,
acpcurso.nome as acpcurso_nome,
acpcurso.nomeparadocumentos as acpcurso_nomeparadocumentos,
acpcurso.descricao as acpcurso_descricao,
acpcurso.modalidade as acpcurso_modalidade,
acpcurso.disciplinasadistancia as acpcurso_disciplinasadistancia,
acpcurso.percentualcargahorariadistancia as acpcurso_percentualcargahorariadistancia,
acpcurso.titulacao as acpcurso_titulacao,
acpcurso.numeroformalvagas as acpcurso_numeroformalvagas,
acpcurso.situacao as acpcurso_situacao,
acpcurso.datainicio as acpcurso_datainicio,
acpcurso.datafim as acpcurso_datafim,
acpcurso.gratuito as acpcurso_gratuito,
acpcurso.percentualmultadesistencia as acpcurso_percentualmultadesistencia,
acpmatricula.username as acpmatricula_username,
acpmatricula.datetime as acpmatricula_datetime,
acpmatricula.ipaddress as acpmatricula_ipaddress,
acpmatricula.matriculaid as acpmatricula_matriculaid,
acpmatricula.ofertacomponentecurricularid as acpmatricula_ofertacomponentecurricularid,
acpinscricaoturmagrupo.inscricaoid as acpmatricula_inscricaoid,
acpmatricula.personid as acpmatricula_personid,
acpmatricula.situacao as acpmatricula_situacao,
acpmatricula.datamatricula as acpmatricula_datamatricula,
acpmatricula.estadodematriculaid as acpmatricula_estadodematriculaid,
acpmatricula.notafinal as acpmatricula_notafinal,
acpmatricula.conceitofinal as acpmatricula_conceitofinal,
acpmatricula.parecerfinal as acpmatricula_parecerfinal,
acpmatricula.faltas as acpmatricula_faltas,
acpmatricula.unitid as acpmatricula_unitid,
(SELECT documento
   FROM acp_obterAtoRegulatorioVigente(acpocorrenciacurso.ocorrenciacursoid)) AS ato_regulatorio_vigente,
X.quantidade_cursos AS quantidade_cursos,
X.carga_horaria AS carga_horaria_total,
XY.carga_horaria AS carga_horaria_tcc,
(SELECT nome
   FROM acpGrauAcademico
  WHERE grauAcademicoId = acpcurso.grauacademicoid) AS grau_academico
From
       acpinscricao
         Left Join acpinscricaoturmagrupo on acpinscricao.inscricaoid=acpinscricaoturmagrupo.inscricaoid
          Left Join basphysicalpersonstudent on acpinscricao.personid=basphysicalpersonstudent.personid
           Left Join basperson on basphysicalpersonstudent.personid=basperson.personid
            Left Join basdocument on basdocument.personid=basperson.personid
             Left Join basdocumenttype on basdocument.documenttypeid=basdocumenttype.documenttypeid
         Left Join acpofertaturma on acpinscricaoturmagrupo.ofertaturmaid=acpofertaturma.ofertaturmaid
          Left Join acpofertacomponentecurricular on acpofertacomponentecurricular.ofertaturmaid=acpofertaturma.ofertaturmaid
           Left Join acpofertacurso on acpofertaturma.ofertacursoid=acpofertacurso.ofertacursoid
            Left Join acpocorrenciacurso on acpofertacurso.ocorrenciacursoid=acpocorrenciacurso.ocorrenciacursoid
             Left Join acpcurso on acpocorrenciacurso.cursoid=acpcurso.cursoid
         Left Join acpmatricula on acpmatricula.inscricaoturmagrupoid=acpinscricaoturmagrupo.inscricaoturmagrupoid
 LEFT JOIN (SELECT MC.cursoId,
                   count(CC.componenteCurricularId) AS quantidade_cursos,
                   sum(CCD.cargahoraria) AS carga_horaria
              FROM acpcomponentecurricularmatriz CCM
        INNER JOIN acpComponenteCurricular CC
             USING (componenteCurricularId)
        INNER JOIN acpMatrizCurricularGrupo MCG
                ON MCG.matrizCurricularGrupoId = CCM.matrizCurricularGrupoId
        INNER JOIN acpMatrizCurricular MC
                ON MC.matrizCurricularId = MCG.matrizCurricularId
        INNER JOIN acpComponenteCurricularDisciplina CCD
                ON CCD.componenteCurricularId = CC.componenteCurricularId
          GROUP BY MC.cursoId) X
        ON X.cursoId = acpocorrenciacurso.cursoid
 LEFT JOIN (SELECT MC.cursoId,
                   sum(CTC.cargahoraria) AS carga_horaria
              FROM acpcomponentecurricularmatriz CCM
        INNER JOIN acpComponenteCurricular CC
             USING (componenteCurricularId)
        INNER JOIN acpMatrizCurricularGrupo MCG
                ON MCG.matrizCurricularGrupoId = CCM.matrizCurricularGrupoId
        INNER JOIN acpMatrizCurricular MC
                ON MC.matrizCurricularId = MCG.matrizCurricularId
        INNER JOIN acpcomponentecurriculartrabalhoconclusao CTC
                ON CTC.componenteCurricularId = CC.componenteCurricularId
                GROUP BY MC.cursoId) XY
                ON XY.cursoId = acpocorrenciacurso.cursoid;