CREATE OR REPLACE VIEW resultado_avaliacao_para_relatorio AS (
SELECT A.id_respostas, 
       A.ref_avaliacao, 
       A.nome_avaliacao, 
       A.id_formulario, 
       A.nome_formulario, 
       A.ref_perfil, 
       A.nome_perfil, 
       A.id_bloco, 
       A.nome_bloco, 
       A.id_granularidade, 
       A.nome_granularidade, 
       A.tipo_granularidade, 
       A.id_questoes, 
       A.nome_questoes, 
       A.tipo, 
       B.codigo,
       A.resposta,
       (CASE WHEN A.resposta = B.codigo THEN 1 ELSE 0 END) as "opcao_escolhida", 
       B.descricao, 
       COALESCE(B.legenda, B.descricao) as "legenda",
       A.ref_resposta, 
       A.course_name, 
       A.ref_curso, 
       A.ref_unit, 
       A.ref_course, 
       A.person_maritalstatus_description, 
       A.groupid, 
       A.curricularcomponentversion, 
       A.ref_sector, 
       A.formation_level, 
       A.ref_group, 
       A.ref_curricular_component, 
       A.person_cityid, 
       A.person_employee_description, 
       A.ref_curriculum, 
       A.course, 
       A.turn, 
       A.course_centerid, 
       A.person_sex, 
       A.professor_name, 
       A.person_employee_typeid, 
       A.person_stateid, 
       A.person_state_description, 
       A.person_maritalstatusid, 
       A.totalenrolled, 
       A.person_weeklyhours, 
       A.person_city_description, 
       A.sector, 
       A.ref_turn, 
       A.curricular_component, 
       A.professorid, 
       A.ref_formation_level, 
       A.ref_curriculum_version, 
       A.course_center_description, 
       A.person_datebirth, 
       A.course_version, 
       A.person_specialnecessityid, 
       A.ref_unidade, 
       A.person_regimetrabalho, 
       A.unit, 
       A.ref_curricular_component_version, 
       A.person_specialnecessity_description, 
       A.ref_turno, 
       A.courseverion 
  FROM resultado_avaliacao A 
LEFT JOIN ava_questoes_opcoes B
        ON (A.id_questoes = B.ref_questoes)
     WHERE A.tipo IN (2,3,4));
